default:
	gcc -Wall int_binary_search_tree.c -o int_binary_search_tree -lm
	gcc -Wall float_binary_search_tree.c -o float_binary_search_tree -lm
	gcc -Wall string_binary_search_tree.c -o string_binary_search_tree -lm

debug:
	gcc -Wall -g int_binary_search_tree.c -o int_binary_search_tree -lm
	gcc -Wall -g float_binary_search_tree.c -o float_binary_search_tree -lm
	gcc -Wall -g string_binary_search_tree.c -o string_binary_search_tree -lm

clean:
	echo "Cleaning up...."
	rm -f int_binary_search_tree
	rm -f float_binary_search_tree
	rm -f string_binary_search_tree
	echo "Done!"
