default:
	gcc -Wall intArrayList.c -o intArrayList
	gcc -Wall doubleArrayList.c -o doubleArrayList

debug:
	gcc -Wall -g intArrayList.c -o intArrayList
	gcc -Wall -g doubleArrayList.c -o doubleArrayList

debug2:
	gcc -Wall -std=c11 -ggdb3 intArrayList.c -o intArrayList
	gcc -Wall -std=c11 -ggdb3 doubleArrayList.c -o doubleArrayList

clean:
	rm intArrayList
	rm doubleArrayList

