default:
	gcc -Wall intArrayList.c -o intArrayList
	gcc -Wall doubleArrayList.c -o doubleArrayList
	gcc -Wall strArrayList.c -o strArrayList

debug:
	gcc -Wall -g intArrayList.c -o intArrayList
	gcc -Wall -g doubleArrayList.c -o doubleArrayList
	gcc -Wall -g strArrayList.c -o strArrayList

debug2:
	gcc -Wall -std=c11 -ggdb3 intArrayList.c -o intArrayList
	gcc -Wall -std=c11 -ggdb3 doubleArrayList.c -o doubleArrayList
	gcc -Wall -std=c11 -ggdb3 strArrayList.c -o strArrayList

clean:
	rm intArrayList
	rm doubleArrayList
	rm strArrayList

