default:
	gcc -Wall int_array_queue.c -o int_array_queue
	gcc -Wall float_array_queue.c -o float_array_queue
	gcc -Wall string_array_queue.c -o string_array_queue

debug:
	gcc -Wall -g int_array_queue.c -o int_array_queue
	gcc -Wall -g float_array_queue.c -o float_array_queue
	gcc -Wall -g string_array_queue.c -o string_array_queue

clean:
	echo "Cleaning up...."
	rm -f int_array_queue
	rm -f float_array_queue
	rm -f string_array_queue
	echo "Done!"
