default:
	gcc -Wall int_stack_array.c -o int_stack_array
	gcc -Wall float_stack_array.c -o float_stack_array
	gcc -Wall string_stack_array.c -o string_stack_array

debug:
	gcc -Wall -g int_stack_array.c -o int_stack_array
	gcc -Wall -g float_stack_array.c -o float_stack_array
	gcc -Wall -g string_stack_array.c -o string_stack_array

clean:
	echo "Cleaning up...."
	rm -f int_stack_array
	rm -f float_stack_array
	rm -f string_stack_array
	echo "Done!"
