install:
	g++ -Wall -c linkedListNode.cpp
	g++ -Wall -c linkedList.cpp
	g++ -Wall *.o -o linkedList

debug:
	g++ -Wall -g -c linkedListNode.cpp
	g++ -Wall -g -c linkedList.cpp
	g++ -Wall -g *.o -o linkedList

clean:
	rm -f *.o
	rm -f linkedListNode
	rm -f linkedList
