install:
	g++ -Wall -c linkedListNode.cpp 
	g++ -Wall -c linkedList.cpp 
	g++ -o linkedList linkedListNode.o linkedList.o -lm

debug:
	g++ -Wall -g linkedListNode.cpp -o linkedListNode

clean:
	rm -f linkedListNode
	rm -f linkedList

