default:
	gcc -Wall int_stack_llist.c -o int_stack_llist
	gcc -Wall float_stack_llist.c -o float_stack_llist
	gcc -Wall string_stack_llist.c -o string_stack_llist

debug:
	gcc -Wall -g int_stack_llist.c -o int_stack_llist
	gcc -Wall -g float_stack_llist.c -o float_stack_llist
	gcc -Wall -g string_stack_llist.c -o string_stack_llist

clean:
	echo "Cleaning up...."
	rm -f int_stack_llist
	rm -f float_stack_llist
	rm -f string_stack_llist
	echo "Done!"
