default:
	gcc -Wall int_queue_linked.c -o int_queue_linked

debug:
	gcc -Wall -g int_queue_linked.c -o int_queue_linked

clean:
	echo "Cleaning up...."
	rm -f int_queue_linked
	rm -f float_queue_linked
	rm -f string_queue_linked
	echo "Done!"
