default:
	gcc -Wall int_linked_list.c -o int_linked_list
	gcc -Wall float_linked_list.c -o float_linked_list
	gcc -Wall string_linked_list.c -o string_linked_list

debug:
	gcc -Wall -g int_linked_list.c -o int_linked_list
	gcc -Wall -g float_linked_list.c -o float_linked_list
	gcc -Wall -g string_linked_list.c -o string_linked_list

clean:
	echo "Cleaning up...."
	rm -f int_linked_list
	rm -f float_linked_list
	rm -f string_linked_list
	echo "Done!"
